/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * This file was generated by scripts/codegen.ts
 *
 * Original abi file:
 * - node_modules/@axelar-network/interchain-token-service/artifacts/contracts/interfaces/ITokenManagerDeployer.sol/ITokenManagerDeployer.json
 *
 * DO NOT EDIT MANUALLY
 */

import { Chain } from "viem";

import { PublicContractClient } from "../../PublicContractClient";
import ABI_FILE from "./ITokenManagerDeployer.abi";

export * from "./ITokenManagerDeployer.args";

export const ITOKEN_MANAGER_DEPLOYER_ABI = ABI_FILE.abi;

export class ITokenManagerDeployerClient extends PublicContractClient<
  typeof ABI_FILE.abi
> {
  static ABI = ABI_FILE.abi;
  static contractName = ABI_FILE.contractName;

  constructor(options: { chain: Chain; address: `0x${string}` }) {
    super({
      abi: ITOKEN_MANAGER_DEPLOYER_ABI,
      address: options.address,
      chain: options.chain,
    });
  }
}

export const createITokenManagerDeployerClient = (options: {
  chain: Chain;
  address: `0x${string}`;
}) => new ITokenManagerDeployerClient(options);
