/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * This file was generated by scripts/codegen.ts
 *
 * Original abi file:
 * - node_modules/@axelar-network/interchain-token-service/artifacts/contracts/interfaces/ITokenManagerDeployer.sol/ITokenManagerDeployer.json
 *
 * DO NOT EDIT MANUALLY
 */

import { encodeFunctionData } from "viem";

import ABI_FILE from "./ITokenManagerDeployer.abi";

export type ITokenManagerDeployerDeployTokenManagerArgs = {
  tokenId: `0x${string}`;
  implementationType: bigint;
  params: `0x${string}`;
};

/**
 * Factory function for ITokenManagerDeployer.deployTokenManager function args
 */
export const encodeITokenManagerDeployerDeployTokenManagerArgs = ({
  tokenId,
  implementationType,
  params,
}: ITokenManagerDeployerDeployTokenManagerArgs) =>
  [tokenId, implementationType, params] as const;

/**
 * Encoder function for ITokenManagerDeployer.deployTokenManager function data
 */
export const encodeITokenManagerDeployerDeployTokenManagerData = ({
  tokenId,
  implementationType,
  params,
}: ITokenManagerDeployerDeployTokenManagerArgs) =>
  encodeFunctionData({
    functionName: "deployTokenManager",
    abi: ABI_FILE.abi,
    args: [tokenId, implementationType, params],
  });

export const ITOKEN_MANAGER_DEPLOYER_ENCODERS = {
  deployTokenManager: encodeITokenManagerDeployerDeployTokenManagerArgs,
};
