name: "Install dependencies"
description: "setup pnpm cache & install all dependencies"

inputs:
  cache:
    description: "Whether to cache dependencies"
    required: false
    default: "false"

runs:
  using: "composite"

  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      id: pnpm-install
      with:
        version: 8
        run_install: false

    - name: Get pnpm store directory
      if: inputs.cache == 'true'
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Setup pnpm cache
      if: inputs.cache == 'true'
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Setup Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install
