/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * This file was generated by scripts/codegen.ts
 *
 * Original abi file:
 * - node_modules/@axelar-network/interchain-token-service/artifacts/contracts/InterchainTokenFactory.sol/InterchainTokenFactory.json
 *
 * DO NOT EDIT MANUALLY
 */

import { Chain } from "viem";

import { PublicContractClient } from "../../PublicContractClient";
import ABI_FILE from "./InterchainTokenFactory.abi";
import { createInterchainTokenFactoryReadClient } from "./InterchainTokenFactory.args";

const createReadClient = createInterchainTokenFactoryReadClient;

export * from "./InterchainTokenFactory.args";

export const INTERCHAIN_TOKEN_FACTORY_ABI = ABI_FILE.abi;

/**
 * InterchainTokenFactoryClient
 *
 * @description Type-safe contract client for InterchainTokenFactory
 *
 * @example
 *
 * import { sepolia } from "viem/chains";
 *
 * const client = createInterchainTokenFactoryClient({
 *  chain: sepolia,
 *  address: "0x1234..."
 * });
 */
export class InterchainTokenFactoryClient extends PublicContractClient<
  typeof ABI_FILE.abi
> {
  static ABI = ABI_FILE.abi;
  static contractName = ABI_FILE.contractName;

  public readonly reads: ReturnType<typeof createReadClient>;

  constructor(options: { chain: Chain; address: `0x${string}` }) {
    super({
      abi: INTERCHAIN_TOKEN_FACTORY_ABI,
      address: options.address,
      chain: options.chain,
    });

    this.reads = createReadClient(this);
  }
}

export const createInterchainTokenFactoryClient = (options: {
  chain: Chain;
  address: `0x${string}`;
}) => new InterchainTokenFactoryClient(options);
