[package]
name = "GasService"
version = "0.1.0"
edition = "2024.beta"
published-at = "0xe62efdb9f04fe3dba11a2495bb2c3d0e0afb29fd40076a978e883b851d87165d"

[dependencies]
[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "mainnet-v1.32.2"

[dependencies.VersionControl]
local = "../version_control"

[addresses]
gas_service = "0xe62efdb9f04fe3dba11a2495bb2c3d0e0afb29fd40076a978e883b851d87165d"