/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * This file was generated by scripts/codegen.ts
 *
 * Original abi file:
 * - node_modules/@axelar-network/interchain-token-service/artifacts/contracts/interfaces/IGatewayCaller.sol/IGatewayCaller.json
 *
 * DO NOT EDIT MANUALLY
 */

export default {
  contractName: "IGatewayCaller",
  abi: [
    {
      inputs: [
        {
          internalType: "uint32",
          name: "metadataVersion",
          type: "uint32",
        },
      ],
      name: "InvalidMetadataVersion",
      type: "error",
    },
    {
      inputs: [
        {
          internalType: "string",
          name: "destinationChain",
          type: "string",
        },
        {
          internalType: "string",
          name: "destinationAddress",
          type: "string",
        },
        {
          internalType: "bytes",
          name: "payload",
          type: "bytes",
        },
        {
          internalType: "enum IGatewayCaller.MetadataVersion",
          name: "metadataVersion",
          type: "uint8",
        },
        {
          internalType: "uint256",
          name: "gasValue",
          type: "uint256",
        },
      ],
      name: "callContract",
      outputs: [],
      stateMutability: "payable",
      type: "function",
    },
  ],
} as const;
