/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * This file was generated by scripts/codegen.ts
 *
 * Original abi file:
 * - node_modules/@axelar-network/interchain-token-service/artifacts/contracts/interfaces/IInterchainTokenFactory.sol/IInterchainTokenFactory.json
 *
 * DO NOT EDIT MANUALLY
 */

import { Chain } from "viem";

import { PublicContractClient } from "../../PublicContractClient";
import ABI_FILE from "./IInterchainTokenFactory.abi";
import { createIInterchainTokenFactoryReadClient } from "./IInterchainTokenFactory.args";

export * from "./IInterchainTokenFactory.args";

const createReadClient = createIInterchainTokenFactoryReadClient;

export const IINTERCHAIN_TOKEN_FACTORY_ABI = ABI_FILE.abi;

export class IInterchainTokenFactoryClient extends PublicContractClient<
  typeof ABI_FILE.abi
> {
  static ABI = ABI_FILE.abi;
  static contractName = ABI_FILE.contractName;

  public readonly reads: ReturnType<typeof createReadClient>;

  constructor(options: { chain: Chain; address: `0x${string}` }) {
    super({
      abi: IINTERCHAIN_TOKEN_FACTORY_ABI,
      address: options.address,
      chain: options.chain,
    });

    this.reads = createReadClient(this);
  }
}
