const chainsData: Record<
  string,
  { nameID: string; name: string; image: string; isTestnet: boolean }
> = {
  "421614": {
    nameID: "arbitrum-sepolia",
    name: "Arbitrum Sepolia",
    image: "arbitrum.svg",
    isTestnet: true,
  },
  "43113": {
    nameID: "Avalanche",
    name: "Avalanche",
    image: "avalanche.svg",
    isTestnet: true,
  },
  "84532": {
    nameID: "base-sepolia",
    name: "Base Sepolia Testnet",
    image: "base.svg",
    isTestnet: true,
  },
  "97": {
    nameID: "binance",
    name: "BNB Chain",
    image: "binance.svg",
    isTestnet: true,
  },
  "168587773": {
    nameID: "blast-sepolia",
    name: "Blast Sepolia Testnet",
    image: "blast.svg",
    isTestnet: true,
  },
  "44787": {
    nameID: "celo",
    name: "Celo",
    image: "celo.svg",
    isTestnet: true,
  },
  "11155111": {
    nameID: "ethereum-sepolia",
    name: "Ethereum Sepolia",
    image: "ethereum.svg",
    isTestnet: true,
  },
  "4002": {
    nameID: "Fantom",
    name: "Fantom",
    image: "fantom.svg",
    isTestnet: true,
  },
  "314159": {
    nameID: "filecoin-2",
    name: "Filecoin",
    image: "filecoin.svg",
    isTestnet: true,
  },
  "2522": {
    nameID: "fraxtal",
    name: "Fraxtal",
    image: "fraxtal.svg",
    isTestnet: true,
  },
  "2221": {
    nameID: "kava",
    name: "Kava",
    image: "kava.svg",
    isTestnet: true,
  },
  "5003": {
    nameID: "mantle-sepolia",
    name: "Mantle Sepolia",
    image: "mantle.svg",
    isTestnet: true,
  },
  "1287": {
    nameID: "Moonbeam",
    name: "Moonbase",
    image: "moonbeam.svg",
    isTestnet: true,
  },
  "11155420": {
    nameID: "optimism-sepolia",
    name: "Optimism Sepolia Testnet",
    image: "optimism.svg",
    isTestnet: true,
  },
  "80001": {
    nameID: "Polygon",
    name: "Polygon",
    image: "polygon.svg",
    isTestnet: true,
  },
  "534351": {
    nameID: "scroll",
    name: "Scroll",
    image: "scroll.svg",
    isTestnet: true,
  },
  "5611": {
    nameID: "binance",
    name: "BNB",
    image: "binance.png",
    isTestnet: true,
  },
  "59140": {
    nameID: "linea",
    name: "Linea",
    image: "linea.svg",
    isTestnet: true,
  },
  "42161": {
    nameID: "arbitrum",
    name: "Arbitrum",
    image: "arbitrum.svg",
    isTestnet: false,
  },
  "43114": {
    nameID: "Avalanche",
    name: "Avalanche",
    image: "avalanche.svg",
    isTestnet: false,
  },
  "8453": {
    nameID: "base",
    name: "Base",
    image: "base.svg",
    isTestnet: false,
  },
  "56": {
    nameID: "binance",
    name: "BNB Chain",
    image: "binance.png",
    isTestnet: false,
  },
  "81457": {
    nameID: "blast",
    name: "Blast",
    image: "blast.svg",
    isTestnet: false,
  },
  "42220": {
    nameID: "celo",
    name: "Celo",
    image: "celo.svg",
    isTestnet: false,
  },
  "2031": {
    nameID: "centrifuge",
    name: "Centrifuge",
    image: "centrifuge.svg",
    isTestnet: false,
  },
  "1": {
    nameID: "Ethereum",
    name: "Ethereum",
    image: "ethereum.svg",
    isTestnet: false,
  },
  "250": {
    nameID: "Fantom",
    name: "Fantom",
    image: "fantom.svg",
    isTestnet: false,
  },
  "314": {
    nameID: "filecoin",
    name: "Filecoin",
    image: "filecoin.svg",
    isTestnet: false,
  },
  "252": {
    nameID: "fraxtal",
    name: "Fraxtal",
    image: "fraxtal.svg",
    isTestnet: false,
  },
  "2222": {
    nameID: "kava",
    name: "Kava",
    image: "kava.svg",
    isTestnet: false,
  },
  "59144": {
    nameID: "linea",
    name: "Linea",
    image: "linea.svg",
    isTestnet: false,
  },
  "5000": {
    nameID: "mantle",
    name: "Mantle",
    image: "mantle.svg",
    isTestnet: false,
  },
  "1284": {
    nameID: "Moonbeam",
    name: "Moonbeam",
    image: "moonbeam.svg",
    isTestnet: false,
  },
  "10": {
    nameID: "optimism",
    name: "Optimism",
    image: "optimism.svg",
    isTestnet: false,
  },
  "137": {
    nameID: "Polygon",
    name: "Polygon",
    image: "polygon.svg",
    isTestnet: false,
  },
  "534352": {
    nameID: "scroll",
    name: "Scroll",
    image: "scroll.svg",
    isTestnet: false,
  },
};
export default chainsData;
