[package]
name = "Squid"
version = "0.1.0"
edition = "2024.beta"
published-at = "0x0"

[dependencies]
[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "mainnet-v1.32.2"

[dependencies.deepbook]
git = "https://github.com/MystenLabs/deepbookv3.git"
subdir = "packages/deepbook"
rev = "deepbook/mainnet-1.32.2"

[dependencies.token]
git = "https://github.com/MystenLabs/deepbookv3.git"
subdir = "packages/token"
rev = "deepbook/mainnet-1.32.2"

[dependencies.Utils]
local = "../utils"

[dependencies.AxelarGateway]
local = "../axelar_gateway"

[dependencies.ITS]
local = "../its"

[dependencies.VersionControl]
local = "../version_control"

[dependencies.RelayerDiscovery]
local = "../relayer_discovery"

[addresses]
squid = "0x0"