/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * This file was generated by scripts/codegen.ts
 *
 * Original abi file:
 * - node_modules/@axelar-network/interchain-token-service/artifacts/contracts/TokenHandler.sol/TokenHandler.json
 *
 * DO NOT EDIT MANUALLY
 */

import { encodeFunctionData } from "viem";

import ABI_FILE from "./TokenHandler.abi";

export type TokenHandlerGiveTokenArgs = {
  tokenManagerType: bigint;
  tokenAddress: `0x${string}`;
  tokenManager: `0x${string}`;
  to: `0x${string}`;
  amount: bigint;
};

/**
 * Factory function for TokenHandler.giveToken function args
 */
export const encodeTokenHandlerGiveTokenArgs = ({
  tokenManagerType,
  tokenAddress,
  tokenManager,
  to,
  amount,
}: TokenHandlerGiveTokenArgs) =>
  [tokenManagerType, tokenAddress, tokenManager, to, amount] as const;

/**
 * Encoder function for TokenHandler.giveToken function data
 */
export const encodeTokenHandlerGiveTokenData = ({
  tokenManagerType,
  tokenAddress,
  tokenManager,
  to,
  amount,
}: TokenHandlerGiveTokenArgs): `0x${string}` =>
  encodeFunctionData({
    functionName: "giveToken",
    abi: ABI_FILE.abi,
    args: [tokenManagerType, tokenAddress, tokenManager, to, amount],
  });

export type TokenHandlerTakeTokenArgs = {
  tokenManagerType: bigint;
  tokenAddress: `0x${string}`;
  tokenManager: `0x${string}`;
  from: `0x${string}`;
  amount: bigint;
};

/**
 * Factory function for TokenHandler.takeToken function args
 */
export const encodeTokenHandlerTakeTokenArgs = ({
  tokenManagerType,
  tokenAddress,
  tokenManager,
  from,
  amount,
}: TokenHandlerTakeTokenArgs) =>
  [tokenManagerType, tokenAddress, tokenManager, from, amount] as const;

/**
 * Encoder function for TokenHandler.takeToken function data
 */
export const encodeTokenHandlerTakeTokenData = ({
  tokenManagerType,
  tokenAddress,
  tokenManager,
  from,
  amount,
}: TokenHandlerTakeTokenArgs): `0x${string}` =>
  encodeFunctionData({
    functionName: "takeToken",
    abi: ABI_FILE.abi,
    args: [tokenManagerType, tokenAddress, tokenManager, from, amount],
  });

export type TokenHandlerTransferTokenFromArgs = {
  tokenManagerType: bigint;
  tokenAddress: `0x${string}`;
  from: `0x${string}`;
  to: `0x${string}`;
  amount: bigint;
};

/**
 * Factory function for TokenHandler.transferTokenFrom function args
 */
export const encodeTokenHandlerTransferTokenFromArgs = ({
  tokenManagerType,
  tokenAddress,
  from,
  to,
  amount,
}: TokenHandlerTransferTokenFromArgs) =>
  [tokenManagerType, tokenAddress, from, to, amount] as const;

/**
 * Encoder function for TokenHandler.transferTokenFrom function data
 */
export const encodeTokenHandlerTransferTokenFromData = ({
  tokenManagerType,
  tokenAddress,
  from,
  to,
  amount,
}: TokenHandlerTransferTokenFromArgs): `0x${string}` =>
  encodeFunctionData({
    functionName: "transferTokenFrom",
    abi: ABI_FILE.abi,
    args: [tokenManagerType, tokenAddress, from, to, amount],
  });

export const TOKEN_HANDLER_ENCODERS = {
  giveToken: {
    args: encodeTokenHandlerGiveTokenArgs,
    data: encodeTokenHandlerGiveTokenData,
  },
  takeToken: {
    args: encodeTokenHandlerTakeTokenArgs,
    data: encodeTokenHandlerTakeTokenData,
  },
  transferTokenFrom: {
    args: encodeTokenHandlerTransferTokenFromArgs,
    data: encodeTokenHandlerTransferTokenFromData,
  },
};
