/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * This file was generated by scripts/codegen.ts
 *
 * Original abi file:
 * - node_modules/@axelar-network/interchain-token-service/artifacts/contracts/interfaces/IOperator.sol/IOperator.json
 *
 * DO NOT EDIT MANUALLY
 */

import { Chain } from "viem";

import { PublicContractClient } from "../../PublicContractClient";
import ABI_FILE from "./IOperator.abi";
import { createIOperatorReadClient } from "./IOperator.args";

const createReadClient = createIOperatorReadClient;

export * from "./IOperator.args";

export const IOPERATOR_ABI = ABI_FILE.abi;

export class IOperatorClient extends PublicContractClient<typeof ABI_FILE.abi> {
  static ABI = ABI_FILE.abi;
  static contractName = ABI_FILE.contractName;

  public readonly reads: ReturnType<typeof createReadClient>;

  constructor(options: { chain: Chain; address: `0x${string}` }) {
    super({
      abi: IOPERATOR_ABI,
      address: options.address,
      chain: options.chain,
    });

    this.reads = createReadClient(this);
  }
}

export const createIOperatorClient = (options: {
  chain: Chain;
  address: `0x${string}`;
}) => new IOperatorClient(options);
