/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * This file was generated by scripts/codegen.ts
 *
 * Original abi file:
 * - node_modules/@axelar-network/interchain-token-service/artifacts/contracts/interfaces/IAddressTracker.sol/IAddressTracker.json
 *
 * DO NOT EDIT MANUALLY
 */

import { encodeFunctionData } from "viem";

import type { PublicContractClient } from "../../PublicContractClient";
import ABI_FILE from "./IAddressTracker.abi";

export type IAddressTrackerIsTrustedAddressArgs = {
  chain: string;
  address_: string;
};

/**
 * Factory function for IAddressTracker.isTrustedAddress function args
 */
export const encodeIAddressTrackerIsTrustedAddressArgs = ({
  chain,
  address_,
}: IAddressTrackerIsTrustedAddressArgs) => [chain, address_] as const;

/**
 * Encoder function for IAddressTracker.isTrustedAddress function data
 */
export const encodeIAddressTrackerIsTrustedAddressData = ({
  chain,
  address_,
}: IAddressTrackerIsTrustedAddressArgs): `0x${string}` =>
  encodeFunctionData({
    functionName: "isTrustedAddress",
    abi: ABI_FILE.abi,
    args: [chain, address_],
  });

export type IAddressTrackerRemoveTrustedAddressArgs = { chain: string };

/**
 * Factory function for IAddressTracker.removeTrustedAddress function args
 */
export const encodeIAddressTrackerRemoveTrustedAddressArgs = ({
  chain,
}: IAddressTrackerRemoveTrustedAddressArgs) => [chain] as const;

/**
 * Encoder function for IAddressTracker.removeTrustedAddress function data
 */
export const encodeIAddressTrackerRemoveTrustedAddressData = ({
  chain,
}: IAddressTrackerRemoveTrustedAddressArgs): `0x${string}` =>
  encodeFunctionData({
    functionName: "removeTrustedAddress",
    abi: ABI_FILE.abi,
    args: [chain],
  });

export type IAddressTrackerSetTrustedAddressArgs = {
  chain: string;
  address_: string;
};

/**
 * Factory function for IAddressTracker.setTrustedAddress function args
 */
export const encodeIAddressTrackerSetTrustedAddressArgs = ({
  chain,
  address_,
}: IAddressTrackerSetTrustedAddressArgs) => [chain, address_] as const;

/**
 * Encoder function for IAddressTracker.setTrustedAddress function data
 */
export const encodeIAddressTrackerSetTrustedAddressData = ({
  chain,
  address_,
}: IAddressTrackerSetTrustedAddressArgs): `0x${string}` =>
  encodeFunctionData({
    functionName: "setTrustedAddress",
    abi: ABI_FILE.abi,
    args: [chain, address_],
  });

export type IAddressTrackerTrustedAddressArgs = { chain: string };

/**
 * Factory function for IAddressTracker.trustedAddress function args
 */
export const encodeIAddressTrackerTrustedAddressArgs = ({
  chain,
}: IAddressTrackerTrustedAddressArgs) => [chain] as const;

/**
 * Encoder function for IAddressTracker.trustedAddress function data
 */
export const encodeIAddressTrackerTrustedAddressData = ({
  chain,
}: IAddressTrackerTrustedAddressArgs): `0x${string}` =>
  encodeFunctionData({
    functionName: "trustedAddress",
    abi: ABI_FILE.abi,
    args: [chain],
  });

export type IAddressTrackerTrustedAddressHashArgs = { chain: string };

/**
 * Factory function for IAddressTracker.trustedAddressHash function args
 */
export const encodeIAddressTrackerTrustedAddressHashArgs = ({
  chain,
}: IAddressTrackerTrustedAddressHashArgs) => [chain] as const;

/**
 * Encoder function for IAddressTracker.trustedAddressHash function data
 */
export const encodeIAddressTrackerTrustedAddressHashData = ({
  chain,
}: IAddressTrackerTrustedAddressHashArgs): `0x${string}` =>
  encodeFunctionData({
    functionName: "trustedAddressHash",
    abi: ABI_FILE.abi,
    args: [chain],
  });

export const IADDRESS_TRACKER_ENCODERS = {
  isTrustedAddress: {
    args: encodeIAddressTrackerIsTrustedAddressArgs,
    data: encodeIAddressTrackerIsTrustedAddressData,
  },
  removeTrustedAddress: {
    args: encodeIAddressTrackerRemoveTrustedAddressArgs,
    data: encodeIAddressTrackerRemoveTrustedAddressData,
  },
  setTrustedAddress: {
    args: encodeIAddressTrackerSetTrustedAddressArgs,
    data: encodeIAddressTrackerSetTrustedAddressData,
  },
  trustedAddress: {
    args: encodeIAddressTrackerTrustedAddressArgs,
    data: encodeIAddressTrackerTrustedAddressData,
  },
  trustedAddressHash: {
    args: encodeIAddressTrackerTrustedAddressHashArgs,
    data: encodeIAddressTrackerTrustedAddressHashData,
  },
};

export function createIAddressTrackerReadClient(
  publicClient: PublicContractClient
) {
  return {
    chainName() {
      return publicClient.read("chainName");
    },
    isTrustedAddress(
      isTrustedAddressArgs: IAddressTrackerIsTrustedAddressArgs
    ) {
      const encoder = IADDRESS_TRACKER_ENCODERS["isTrustedAddress"];
      const encodedArgs = encoder.args(isTrustedAddressArgs);

      return publicClient.read("isTrustedAddress", { args: encodedArgs });
    },
    trustedAddress(trustedAddressArgs: IAddressTrackerTrustedAddressArgs) {
      const encoder = IADDRESS_TRACKER_ENCODERS["trustedAddress"];
      const encodedArgs = encoder.args(trustedAddressArgs);

      return publicClient.read("trustedAddress", { args: encodedArgs });
    },
    trustedAddressHash(
      trustedAddressHashArgs: IAddressTrackerTrustedAddressHashArgs
    ) {
      const encoder = IADDRESS_TRACKER_ENCODERS["trustedAddressHash"];
      const encodedArgs = encoder.args(trustedAddressHashArgs);

      return publicClient.read("trustedAddressHash", { args: encodedArgs });
    },
  };
}
