/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * This file was generated by scripts/codegen.ts
 *
 * Original abi file:
 * - node_modules/@axelar-network/interchain-token-service/artifacts/contracts/interfaces/IERC20BurnableFrom.sol/IERC20BurnableFrom.json
 *
 * DO NOT EDIT MANUALLY
 */

import { Chain } from "viem";

import { PublicContractClient } from "../../PublicContractClient";
import ABI_FILE from "./IERC20BurnableFrom.abi";

export * from "./IERC20BurnableFrom.args";

export const IERC20_BURNABLE_FROM_ABI = ABI_FILE.abi;

/**
 * IERC20BurnableFromClient
 *
 * @description Type-safe contract client for IERC20BurnableFrom
 *
 * @example
 *
 * import { sepolia } from "viem/chains";
 *
 * const client = createIERC20BurnableFromClient({
 *  chain: sepolia,
 *  address: "0x1234..."
 * });
 */
export class IERC20BurnableFromClient extends PublicContractClient<
  typeof ABI_FILE.abi
> {
  static ABI = ABI_FILE.abi;
  static contractName = ABI_FILE.contractName;

  constructor(options: { chain: Chain; address: `0x${string}` }) {
    super({
      abi: IERC20_BURNABLE_FROM_ABI,
      address: options.address,
      chain: options.chain,
    });
  }
}

export const createIERC20BurnableFromClient = (options: {
  chain: Chain;
  address: `0x${string}`;
}) => new IERC20BurnableFromClient(options);
