/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

/* Generated types for 0x9d817589ae367cc3f3bc9ca40394be79e5853bfca98014f27acfd4da9db78421, original address 0x9d817589ae367cc3f3bc9ca40394be79e5853bfca98014f27acfd4da9db78421 */

import { TypeDescriptor, ANY_TYPE } from "@typemove/move";
import { MoveCoder, TypedEventInstance } from "@typemove/sui";

import { defaultMoveCoder } from "@typemove/sui";

import {
  ZERO_ADDRESS,
  TypedDevInspectResults,
  getMoveCoder,
} from "@typemove/sui";
import {
  Transaction,
  TransactionArgument,
  TransactionObjectArgument,
} from "@mysten/sui/transactions";
import { SuiClient } from "@mysten/sui/client";
import {
  transactionArgumentOrObject,
  transactionArgumentOrVec,
  transactionArgumentOrPure,
  transactionArgumentOrPureU8,
  transactionArgumentOrPureU16,
  transactionArgumentOrPureU32,
  transactionArgumentOrPureU64,
  transactionArgumentOrPureU128,
  transactionArgumentOrPureU256,
  transactionArgumentOrPureBool,
  transactionArgumentOrPureString,
  transactionArgumentOrPureAddress,
} from "@typemove/sui";

export namespace utils {
  export namespace builder {}
  export namespace view {}
}

const MODULES = JSON.parse(
  '{"utils":{"fileFormatVersion":6,"address":"0x9d817589ae367cc3f3bc9ca40394be79e5853bfca98014f27acfd4da9db78421","name":"utils","friends":[],"structs":{},"exposedFunctions":{}}}',
);

export function loadAllTypes(coder: MoveCoder) {
  for (const m of Object.values(MODULES)) {
    coder.load(
      m as any,
      "0x9d817589ae367cc3f3bc9ca40394be79e5853bfca98014f27acfd4da9db78421",
    );
  }
}

loadAllTypes(defaultMoveCoder());
