import {
  arbitrum,
  arbitrumGoerli,
  aurora,
  auroraTestnet,
  avalanche,
  avalancheFuji,
  baseGoerli,
  bsc,
  bscTestnet,
  celo,
  celoAlfajores,
  fantom,
  fantomTestnet,
  filecoin,
  filecoinCalibration,
  goerli,
  kava,
  kavaTestnet,
  lineaTestnet,
  mainnet,
  moonbaseAlpha,
  moonbeam,
  optimism,
  optimismGoerli,
  polygon,
  polygonMumbai,
  polygonZkEvm,
  polygonZkEvmTestnet,
} from "wagmi/chains";

import { NEXT_PUBLIC_NETWORK_ENV } from "./env";

export const EVM_CHAIN_CONFIGS = [
  {
    ...mainnet,
    axelarChainId: "ethereum",
    axelarChainName: "ethereum",
    environment: "mainnet",
  },
  {
    ...goerli,
    axelarChainId: "ethereum-2",
    axelarChainName: "ethereum-2",
    environment: "testnet",
  },
  {
    ...moonbeam,
    axelarChainId: "moonbeam",
    axelarChainName: "Moonbeam",
    environment: "mainnet",
  },
  {
    ...moonbaseAlpha,
    axelarChainId: "moonbeam",
    axelarChainName: "Moonbeam",
    environment: "testnet",
  },
  {
    ...fantom,
    axelarChainId: "fantom",
    axelarChainName: "Fantom",
    environment: "mainnet",
  },
  {
    ...fantomTestnet,
    axelarChainId: "fantom",
    axelarChainName: "Fantom",
    environment: "testnet",
  },
  {
    ...avalanche,
    axelarChainId: "avalanche",
    axelarChainName: "Avalanche",
    environment: "mainnet",
  },
  {
    ...avalancheFuji,
    axelarChainId: "avalanche",
    axelarChainName: "Avalanche",
    environment: "testnet",
  },
  {
    ...polygon,
    axelarChainId: "polygon",
    axelarChainName: "Polygon",
    environment: "mainnet",
  },
  {
    ...polygonMumbai,
    rpcUrls: {
      default: { http: ["https://polygon-testnet.public.blastapi.io"] },
      public: { http: ["https://polygon-testnet.public.blastapi.io"] },
    },
    axelarChainId: "polygon",
    axelarChainName: "Polygon",
    environment: "testnet",
  },
  {
    ...polygonZkEvm,
    axelarChainId: "polygon-zkevm",
    axelarChainName: "polygon-zkevm",
    environment: "mainnet",
  },
  {
    ...polygonZkEvmTestnet,
    axelarChainId: "polygon-zkevm",
    axelarChainName: "polygon-zkevm",
    environment: "testnet",
  },
  {
    ...bsc,
    axelarChainId: "binance",
    axelarChainName: "binance",
    environment: "mainnet",
  },
  {
    ...bscTestnet,
    axelarChainId: "binance",
    axelarChainName: "binance",
    environment: "testnet",
  },
  {
    ...arbitrum,
    axelarChainId: "arbitrum",
    axelarChainName: "arbitrum",
    environment: "mainnet",
  },
  {
    ...arbitrumGoerli,
    axelarChainId: "arbitrum",
    axelarChainName: "arbitrum",
    environment: "testnet",
  },
  {
    ...celo,
    axelarChainId: "celo",
    axelarChainName: "celo",
    environment: "mainnet",
  },
  {
    ...celoAlfajores,
    axelarChainId: "celo",
    axelarChainName: "celo",
    environment: "testnet",
  },
  {
    ...aurora,
    axelarChainId: "aurora",
    axelarChainName: "aurora",
    environment: "mainnet",
  },
  {
    ...auroraTestnet,
    axelarChainId: "aurora",
    axelarChainName: "aurora",
    environment: "testnet",
  },
  {
    ...optimism,
    axelarChainId: "optimism",
    axelarChainName: "optimism",
    environment: "mainnet",
  },
  {
    ...optimismGoerli,
    axelarChainId: "optimism",
    axelarChainName: "optimism",
    environment: "testnet",
  },
  {
    ...kava,
    axelarChainId: "kava",
    axelarChainName: "kava",
    environment: "mainnet",
  },
  {
    ...kavaTestnet,
    axelarChainId: "kava",
    axelarChainName: "kava",
    environment: "testnet",
  },
  {
    ...filecoinCalibration,
    axelarChainId: "filecoin-2",
    environment: "testnet",
  },
  {
    ...filecoin,
    axelarChainId: "filecoin",
    environment: "mainnet",
  },
  {
    ...baseGoerli,
    axelarChainId: "base",
    environment: "testnet",
  },
  {
    ...lineaTestnet,
    axelarChainId: "linea",
    environment: "testnet",
  },
].filter((chain) => chain.environment === NEXT_PUBLIC_NETWORK_ENV);
