import {
  arbitrum,
  arbitrumSepolia,
  aurora,
  auroraTestnet,
  avalanche,
  avalancheFuji,
  base,
  baseSepolia,
  blast,
  blastSepolia,
  bsc,
  bscTestnet,
  celo,
  celoAlfajores,
  Chain,
  fantom,
  fantomTestnet,
  filecoin,
  filecoinCalibration,
  flowMainnet,
  flowTestnet,
  fraxtal,
  fraxtalTestnet,
  immutableZkEvm,
  immutableZkEvmTestnet,
  kava,
  kavaTestnet,
  linea,
  lineaSepolia,
  lineaTestnet,
  mainnet,
  mantle,
  mantleTestnet,
  moonbaseAlpha,
  moonbeam,
  optimism,
  optimismSepolia,
  polygon,
  polygonAmoy,
  polygonMumbai,
  polygonZkEvm,
  polygonZkEvmTestnet,
  scroll,
  scrollSepolia,
  sepolia,
} from "viem/chains";

import { NEXT_PUBLIC_NETWORK_ENV } from "../env";

export interface ExtendedWagmiChainConfig extends Chain {
  axelarChainId: string;
  axelarChainName: string;
  supportWagmi: boolean;
  environment: "mainnet" | "testnet" | "devnet-amplifier";
}

const ENVIRONMENTS = {
  mainnet: "mainnet",
  devnet: "devnet-amplifier",
  testnet: "testnet",
} as const;

function createRpcUrlConfig(chain: Chain, additionalUrls: string[] = []) {
  const httpUrls = [...chain.rpcUrls.default.http, ...additionalUrls];
  return {
    default: { http: httpUrls },
    public: { http: httpUrls },
  };
}

export const EVM_CHAINS: ExtendedWagmiChainConfig[] = [
  {
    ...mainnet,
    rpcUrls: {
      default: { http: ["https://eth.llamarpc.com", "https://eth.drpc.org"] }, // Temporarily using this url
      public: { http: ["https://eth.llamarpc.com", "https://eth.drpc.org"] },
    },
    axelarChainId: "ethereum",
    axelarChainName: "ethereum",
    supportWagmi: true,
    environment: ENVIRONMENTS.mainnet,
  },
  {
    ...sepolia,
    rpcUrls: {
      default: { http: ["https://rpc-sepolia.rockx.com"] },
      public: { http: ["https://rpc-sepolia.rockx.com"] },
    },
    axelarChainId: "ethereum-sepolia",
    supportWagmi: true,
    axelarChainName: "ethereum-sepolia",
    environment: ENVIRONMENTS.testnet,
  },
  {
    ...flowMainnet,
    axelarChainId: "flow",
    axelarChainName: "Flow",
    supportWagmi: true,
    environment: ENVIRONMENTS.mainnet,
  },
  {
    ...flowTestnet,
    axelarChainId: "flow",
    axelarChainName: "Flow",
    supportWagmi: true,
    environment: ENVIRONMENTS.testnet,
  },
  {
    ...moonbeam,
    rpcUrls: createRpcUrlConfig(moonbeam, ["https://moonbeam.drpc.org"]),
    axelarChainId: "moonbeam",
    axelarChainName: "Moonbeam",
    supportWagmi: true,
    environment: ENVIRONMENTS.mainnet,
  },
  {
    ...moonbaseAlpha,
    axelarChainId: "moonbeam",
    axelarChainName: "Moonbeam",
    supportWagmi: true,
    environment: ENVIRONMENTS.testnet,
  },
  {
    ...fantom,
    rpcUrls: {
      default: { http: ["https://fantom.drpc.org"] },
      public: { http: ["https://fantom.drpc.org"] },
    },
    axelarChainId: "fantom",
    axelarChainName: "Fantom",
    supportWagmi: true,
    environment: ENVIRONMENTS.mainnet,
  },
  {
    ...fantomTestnet,
    axelarChainId: "Fantom",
    axelarChainName: "Fantom",
    supportWagmi: true,
    environment: ENVIRONMENTS.testnet,
  },
  {
    ...immutableZkEvm,
    rpcUrls: createRpcUrlConfig(immutableZkEvm, [
      "https://immutable-zkevm.drpc.org",
    ]),
    axelarChainId: "immutable",
    axelarChainName: "Immutable",
    supportWagmi: true,
    environment: ENVIRONMENTS.mainnet,
  },
  {
    ...immutableZkEvmTestnet,
    axelarChainId: "immutable",
    axelarChainName: "Immutable",
    supportWagmi: true,
    environment: ENVIRONMENTS.testnet,
  },
  {
    ...avalanche,
    rpcUrls: createRpcUrlConfig(avalanche, ["https://1rpc.io/avax/c"]),
    axelarChainId: "avalanche",
    axelarChainName: "Avalanche",
    supportWagmi: true,
    environment: ENVIRONMENTS.mainnet,
  },
  {
    ...avalancheFuji,
    axelarChainId: "Avalanche",
    axelarChainName: "Avalanche",
    supportWagmi: true,
    environment: ENVIRONMENTS.testnet,
  },
  {
    ...polygon,
    rpcUrls: createRpcUrlConfig(polygon, ["https://polygon.llamarpc.com"]),
    axelarChainId: "polygon",
    axelarChainName: "Polygon",
    environment: ENVIRONMENTS.mainnet,
    supportWagmi: true,
  },
  {
    ...polygonAmoy,
    axelarChainId: "polygon-sepolia",
    axelarChainName: "polygon-sepolia",
    environment: ENVIRONMENTS.testnet,
    supportWagmi: true,
  },
  {
    ...polygonZkEvm,
    rpcUrls: createRpcUrlConfig(polygonZkEvm, [
      "https://polygon-zkevm.drpc.org",
    ]),
    axelarChainId: "polygon-zkevm",
    supportWagmi: true,
    axelarChainName: "polygon-zkevm",
    environment: ENVIRONMENTS.mainnet,
  },
  {
    ...polygonZkEvmTestnet,
    axelarChainId: "polygon-zkevm",
    axelarChainName: "polygon-zkevm",
    supportWagmi: true,
    environment: ENVIRONMENTS.testnet,
  },
  {
    ...bsc,
    rpcUrls: createRpcUrlConfig(bsc, ["https://binance.llamarpc.com"]),
    axelarChainId: "binance",
    axelarChainName: "binance",
    supportWagmi: true,
    environment: ENVIRONMENTS.mainnet,
  },
  {
    ...bscTestnet,
    axelarChainId: "binance",
    axelarChainName: "binance",
    supportWagmi: true,
    environment: ENVIRONMENTS.testnet,
  },
  {
    ...arbitrum,
    rpcUrls: createRpcUrlConfig(arbitrum, ["https://arbitrum.drpc.org"]),
    axelarChainId: "arbitrum",
    axelarChainName: "arbitrum",
    supportWagmi: true,
    environment: ENVIRONMENTS.mainnet,
  },
  {
    ...arbitrumSepolia,
    axelarChainId: "arbitrum-sepolia",
    axelarChainName: "arbitrum-sepolia",
    supportWagmi: true,
    environment: ENVIRONMENTS.testnet,
  },
  {
    ...celo,
    rpcUrls: createRpcUrlConfig(celo, ["https://1rpc.io/celo"]),
    axelarChainId: "celo",
    axelarChainName: "celo",
    supportWagmi: true,
    environment: ENVIRONMENTS.mainnet,
  },
  {
    ...celoAlfajores,
    axelarChainId: "celo",
    axelarChainName: "celo",
    supportWagmi: true,
    environment: ENVIRONMENTS.testnet,
  },
  {
    ...aurora,
    rpcUrls: createRpcUrlConfig(aurora, ["https://1rpc.io/aurora"]),
    axelarChainId: "aurora",
    axelarChainName: "aurora",
    supportWagmi: true,
    environment: ENVIRONMENTS.mainnet,
  },
  {
    ...auroraTestnet,
    axelarChainId: "aurora",
    axelarChainName: "aurora",
    supportWagmi: true,
    environment: ENVIRONMENTS.testnet,
  },
  {
    ...optimism,
    axelarChainId: "optimism",
    axelarChainName: "optimism",
    supportWagmi: true,
    environment: ENVIRONMENTS.mainnet,
  },
  {
    ...optimismSepolia,
    axelarChainId: "optimism-sepolia",
    axelarChainName: "optimism-sepolia",
    supportWagmi: true,
    environment: ENVIRONMENTS.testnet,
  },
  {
    ...kava,
    rpcUrls: createRpcUrlConfig(kava, ["https://kava.drpc.org"]),
    axelarChainId: "kava",
    axelarChainName: "kava",
    supportWagmi: true,
    environment: ENVIRONMENTS.mainnet,
  },
  {
    ...kavaTestnet,
    axelarChainId: "kava",
    axelarChainName: "kava",
    environment: ENVIRONMENTS.testnet,
    supportWagmi: true,
  },
  {
    ...filecoinCalibration,
    axelarChainId: "filecoin-2",
    axelarChainName: "filecoin-2",
    supportWagmi: true,
    environment: ENVIRONMENTS.testnet,
  },
  {
    ...filecoin,
    rpcUrls: createRpcUrlConfig(filecoin, ["https://rpc.ankr.com/filecoin"]),
    axelarChainId: "filecoin",
    axelarChainName: "filecoin",
    supportWagmi: true,
    environment: ENVIRONMENTS.mainnet,
  },
  {
    ...base,
    rpcUrls: createRpcUrlConfig(base, ["https://base.llamarpc.com"]),
    axelarChainId: "base",
    axelarChainName: "base",
    supportWagmi: true,
    environment: ENVIRONMENTS.mainnet,
  },
  {
    ...baseSepolia,
    axelarChainId: "base-sepolia",
    axelarChainName: "base-sepolia",
    supportWagmi: true,
    environment: ENVIRONMENTS.testnet,
  },
  {
    ...lineaSepolia,
    axelarChainId: "linea-sepolia",
    axelarChainName: "linea-sepolia",
    supportWagmi: true,
    environment: ENVIRONMENTS.testnet,
  },
  {
    ...lineaTestnet,
    axelarChainId: "linea",
    axelarChainName: "linea",
    supportWagmi: true,
    environment: ENVIRONMENTS.testnet,
  },
  {
    ...linea,
    rpcUrls: createRpcUrlConfig(linea, ["https://1rpc.io/linea"]),
    axelarChainId: "linea",
    axelarChainName: "linea",
    supportWagmi: true,
    environment: ENVIRONMENTS.mainnet,
  },
  {
    ...mantle,
    rpcUrls: createRpcUrlConfig(mantle, ["https://rpc.mantle.xyz"]),
    axelarChainId: "mantle",
    axelarChainName: "mantle",
    supportWagmi: true,
    environment: ENVIRONMENTS.mainnet,
  },
  {
    ...mantleTestnet,
    axelarChainId: "mantle",
    axelarChainName: "mantle",
    supportWagmi: true,
    environment: ENVIRONMENTS.testnet,
  },
  {
    ...scroll,
    rpcUrls: createRpcUrlConfig(scroll, ["https://scroll.drpc.org"]),
    axelarChainId: "scroll",
    axelarChainName: "scroll",
    supportWagmi: true,
    environment: ENVIRONMENTS.mainnet,
  },
  {
    ...scrollSepolia,
    axelarChainId: "scroll",
    axelarChainName: "scroll",
    supportWagmi: true,
    environment: ENVIRONMENTS.testnet,
  },
  {
    ...fraxtal,
    rpcUrls: createRpcUrlConfig(fraxtal, ["https://fraxtal.drpc.org"]),
    axelarChainId: "fraxtal",
    axelarChainName: "fraxtal",
    supportWagmi: true,
    environment: ENVIRONMENTS.mainnet,
  },
  {
    ...fraxtalTestnet,
    axelarChainId: "fraxtal",
    axelarChainName: "fraxtal",
    supportWagmi: true,
    environment: ENVIRONMENTS.testnet,
  },
  {
    ...blast,
    rpcUrls: createRpcUrlConfig(blast, ["https://rpc.envelop.is/blast"]),
    axelarChainId: "blast",
    axelarChainName: "blast",
    supportWagmi: true,
    environment: ENVIRONMENTS.mainnet,
  },
  {
    ...blastSepolia,
    axelarChainId: "blast-sepolia",
    axelarChainName: "blast-sepolia",
    supportWagmi: true,
    environment: ENVIRONMENTS.testnet,
  },
  {
    ...avalancheFuji,
    axelarChainId: "avalanche-fuji",
    axelarChainName: "avalanche-fuji",
    supportWagmi: true,
    environment: ENVIRONMENTS.devnet,
  },
  {
    ...optimismSepolia,
    axelarChainId: "optimism-sepolia",
    axelarChainName: "optimism-sepolia",
    supportWagmi: true,
    environment: ENVIRONMENTS.devnet,
  },
  {
    ...sepolia,
    rpcUrls: {
      default: { http: ["https://rpc-sepolia.rockx.com"] },
      public: { http: ["https://rpc-sepolia.rockx.com"] },
    },
    axelarChainId: "eth-sepolia",
    axelarChainName: "eth-sepolia",
    supportWagmi: true,
    environment: ENVIRONMENTS.devnet,
  },
] as const;

export const EVM_CHAIN_CONFIGS = EVM_CHAINS.filter(
  (chain) => chain.environment === NEXT_PUBLIC_NETWORK_ENV
) as [ExtendedWagmiChainConfig, ...ExtendedWagmiChainConfig[]];
