const feesAndPrices = {
  testnet: [
    {
      name: "test-avalanche",
      amplifierChainId: "test-avalanche",
      description: null,
      gasPriceGwei: 25,
      approvalCost: 250000,
      updated: "2024-09-05",
    },
    {
      name: "test-sepolia",
      amplifierChainId: "test-sepolia",
      description: null,
      gasPriceGwei: 5.02,
      approvalCost: 1300000,
      updated: "2024-08-26",
    },
    {
      name: "flow",
      amplifierChainId: "flow",
      description: null,
      gasPriceGwei: 0.1,
      approvalCost: 250000,
      updated: "2024-09-05",
    },
    {
      name: "hedera",
      amplifierChainId: "hedera",
      description: null,
      gasPriceGwei: 1730,
      approvalCost: 250000,
      updated: "2024-09-18",
    },
  ],
  stagenet: [
    {
      name: "test-avalanche",
      amplifierChainId: "test-avalanche",
      description: null,
      gasPriceGwei: 25,
      approvalCost: 250000,
      updated: "2024-09-05",
    },
    {
      name: "test-sepolia",
      amplifierChainId: "test-sepolia",
      description: null,
      gasPriceGwei: 5.02,
      approvalCost: 1300000,
      updated: "2024-08-05",
    },
    {
      name: "flow",
      amplifierChainId: "flow",
      description: null,
      gasPriceGwei: 0.1,
      approvalCost: 250000,
      updated: "2024-09-05",
    },
    {
      name: "hedera",
      amplifierChainId: "hedera",
      description: null,
      gasPriceGwei: 1730,
      approvalCost: 250000,
      updated: "2024-09-18",
    },
  ],
  "devnet-amplifier": [
    {
      name: "Avalanche",
      amplifierChainId: "avalanche-fuji",
      description: null,
      gasPriceGwei: 25,
      approvalCost: 200000,
      updated: "2024-08-05",
    },
    {
      name: "eth-sepolia",
      amplifierChainId: "eth-sepolia",
      description: null,
      gasPriceGwei: 6.4,
      approvalCost: 200000,
      updated: "2024-08-05",
    },
    {
      name: "optimism-sepolia",
      amplifierChainId: "optimism-sepolia",
      description: null,
      gasPriceGwei: 0.001,
      approvalCost: 300000,
      updated: "2024-08-05",
    },
    {
      name: "flow",
      amplifierChainId: "flow",
      description: null,
      gasPriceGwei: 0.1,
      approvalCost: 250000,
      updated: "2024-09-05",
    },
  ],
  mainnet: [],
};

export default feesAndPrices;
