name: Test (E2E)

on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  wait-for-preview-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Waiting for 200 from the Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1 # <https://github.com/patrickedqvist/wait-for-vercel-preview>
        id: waitForDeploy
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 300

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Install playwright
        run: pnpx playwright install

      - name: Run tests
        env:
          NEXT_PUBLIC_E2E_URL: ${{ steps.waitForDeploy.outputs.url }}
        run: pnpm e2e:maestro
