name: Publish (snapshot versions)

on: workflow_dispatch

jobs:
  snapshot:
    name: Publish Snapshot Versions to NPM
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Create version pull request or publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm changeset:release-snap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
