name: Release (changesets)

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Check for changeset files
        id: checkfile
        run: |
          if ls .changeset/*.md | grep -Eq '^[a-z-]*\.md$'; then
            echo "has_file=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_file=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Install dependencies
        if: steps.checkfile.outputs.has_file == 'true'
        uses: ./.github/actions/install-dependencies

      - name: Create Release Pull Request
        if: steps.checkfile.outputs.has_file == 'true'
        uses: changesets/action@v1
        with:
          title: "[changesets] Apply version updates"
          commit: "chore: apply changesets"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
