name: Test (unit)

on:
  - push
  - pull_request

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout & Install dependencies
        uses: ./.github/actions/checkout-and-install

      - name: Run tests
        run: pnpm test:ci
        env:
          COSMOS_WALLET_MNEMONIC: ${{ secrets.COSMOS_WALLET_MNEMONIC }}
