name: Test (unit)

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run tests
        run: NODE_OPTIONS="--max-old-space-size=4096" pnpm test
        env:
          COSMOS_WALLET_MNEMONIC: ${{ secrets.COSMOS_WALLET_MNEMONIC }}
