/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * This file was generated by scripts/codegen.ts
 *
 * Original abi file:
 * - node_modules/@axelar-network/interchain-token-service/artifacts/contracts/interfaces/ITokenManagerImplementation.sol/ITokenManagerImplementation.json
 *
 * DO NOT EDIT MANUALLY
 */

import { encodeFunctionData } from "viem";

import ABI_FILE from "./ITokenManagerImplementation.abi";

export type ITokenManagerImplementationTokenManagerImplementationArgs = {
  tokenManagerType: bigint;
};

/**
 * Factory function for ITokenManagerImplementation.tokenManagerImplementation function args
 */
export const encodeITokenManagerImplementationTokenManagerImplementationArgs =
  ({
    tokenManagerType,
  }: ITokenManagerImplementationTokenManagerImplementationArgs) =>
    [tokenManagerType] as const;

/**
 * Encoder function for ITokenManagerImplementation.tokenManagerImplementation function data
 */
export const encodeITokenManagerImplementationTokenManagerImplementationData =
  ({
    tokenManagerType,
  }: ITokenManagerImplementationTokenManagerImplementationArgs) =>
    encodeFunctionData({
      functionName: "tokenManagerImplementation",
      abi: ABI_FILE.abi,
      args: [tokenManagerType],
    });

export const ITOKEN_MANAGER_IMPLEMENTATION_ENCODERS = {
  tokenManagerImplementation:
    encodeITokenManagerImplementationTokenManagerImplementationArgs,
};
