/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * This file was generated by scripts/codegen.ts
 *
 * Original abi file:
 * - node_modules/@axelar-network/interchain-token-service/artifacts/contracts/interfaces/ITokenManagerImplementation.sol/ITokenManagerImplementation.json
 *
 * DO NOT EDIT MANUALLY
 */

export default {
  contractName: "ITokenManagerImplementation",
  abi: [
    {
      inputs: [
        {
          internalType: "uint256",
          name: "tokenManagerType",
          type: "uint256",
        },
      ],
      name: "tokenManagerImplementation",
      outputs: [
        {
          internalType: "address",
          name: "tokenManagerAddress_",
          type: "address",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
  ],
} as const;
